/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HeadquaterRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Supplier;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CordinatorWorkRequest;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Am3y
 */
public class InternalProcessJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CordinatorWorkRequest request;
    SupplierOrganization business;
    Enterprise enterprise;
    Organization org;
            
    /**
     * Creates new form InternalProcessJPanel
     */

    InternalProcessJPanel(JPanel userProcessContainer, Organization org, Enterprise enterprise, CordinatorWorkRequest request) {
      initComponents();
      this.userProcessContainer = userProcessContainer;
      this.request = request;
      this.enterprise = enterprise;
      this.org = org;
      txtFunds.setText("600");
      txtRequested.setText(request.getEmployee().getName());
      txtTotal.setText(String.valueOf(request.getTotalBill()));
      populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtRequested = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFunds = new javax.swing.JTextField();
        btnDecline = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbSupplier = new javax.swing.JComboBox<String>();
        btnAssign = new javax.swing.JButton();

        jLabel1.setText("Requested  By:");

        jLabel2.setText("Total Bill:");

        txtTotal.setEnabled(false);

        txtRequested.setEnabled(false);
        txtRequested.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRequestedActionPerformed(evt);
            }
        });

        jLabel3.setText("Funds:");

        txtFunds.setEnabled(false);

        btnDecline.setText("Decline");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        jLabel4.setText("Supplier :");

        cbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSupplierActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(btnAssign))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFunds)
                                .addComponent(txtTotal)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btnDecline))
                                .addComponent(txtRequested))
                            .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel4)))
                .addGap(462, 462, 462))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtRequested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFunds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDecline)
                    .addComponent(btnAssign))
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRequestedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRequestedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRequestedActionPerformed

    private void cbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSupplierActionPerformed

    public void populateComboBox() {
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        System.out.println(org.getName());
        for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
            System.out.println(ua.getUsername());
            if(ua.getRole() instanceof Supplier){
                System.out.println("Found");
                Employee e = ua.getEmployee();
                dm.addElement(e);
            }
        }
        cbSupplier.setModel(dm);
    }
    
    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        
        Employee selectedItem = (Employee) cbSupplier.getSelectedItem();
        if (selectedItem == null) {
            return;
        }
        
        //update Logistics, Investors
        System.out.println("IP: "+request.getEmployee());
        System.out.println(request.getStatus());
        request.setStatus("assigned to Supplier");
        request.setSupplierAssigned(selectedItem);
        System.out.println(request.getStatus());
        selectedItem.addUserRequest(request);
        JOptionPane.showMessageDialog(null, "Supplier assigned successfully");
        
        //back to page
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        initComponents();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
        
        request.setStatus("Declined");
        JOptionPane.showMessageDialog(null, "Declined Successfully!");
        
        //back to page
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_btnDeclineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnDecline;
    private javax.swing.JComboBox<String> cbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFunds;
    private javax.swing.JTextField txtRequested;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
