/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HeadquaterRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Role.CareTaker;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SocialWorkRequest;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 * @author Alekhya
 * @author Apeksha
 * @author Shalini
 */
public class SocialProcessJPanel extends javax.swing.JPanel {

    
    JPanel userProcessContainer;
    SocialWorkRequest request;
    Organization org;
    EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    /**
     * Creates new form SocialProcessJPanel
     */
    public SocialProcessJPanel(JPanel userProcessContainer, Organization org,SocialWorkRequest request, EcoSystem system) {
        initComponents();
        this.request = request;
        this.system = system;
      this.userProcessContainer = userProcessContainer;
      this.org = org;
      txtName.setText(request.getOrg().getName());
      txtZip.setText(request.getZipcode());
      populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbCareTaker = new javax.swing.JComboBox<String>();
        tbnConfirm = new javax.swing.JButton();
        btnDeny = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NGO Name:");

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        txtName.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ZipCode:");

        txtZip.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        txtZip.setEnabled(false);
        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CareTaker:");

        cbCareTaker.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbCareTaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCareTakerActionPerformed(evt);
            }
        });

        tbnConfirm.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbnConfirm.setText("Approve");
        tbnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnConfirmActionPerformed(evt);
            }
        });

        btnDeny.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnDeny.setText("Disapprove");
        btnDeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(85, 85, 85)
                        .addComponent(cbCareTaker, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tbnConfirm)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(77, 77, 77))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(92, 92, 92))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnDeny)))))
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCareTaker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeny)
                    .addComponent(tbnConfirm))
                .addGap(118, 118, 118))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipActionPerformed

    private void cbCareTakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCareTakerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCareTakerActionPerformed

    
    public void populateComboBox() {
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        System.out.println(org.getName());
        for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
            System.out.println(ua.getUsername());
            if(ua.getRole() instanceof CareTaker){
                System.out.println("Found");
                Employee e = ua.getEmployee();
                dm.addElement(e);
            }
        }
        cbCareTaker.setModel(dm);
    }
    
    private void tbnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnConfirmActionPerformed
        // TODO add your handling code here:

        System.out.println("Process: "+request.getUser());
        request.setStatus("Approved");
        Employee ct = (Employee)cbCareTaker.getSelectedItem();
        request.setCareTaker(ct);
        ct.addSocialRequest(request);
        System.out.println(request.getStatus());
        JOptionPane.showMessageDialog(null, "Plantation approved");

        //back to page
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_tbnConfirmActionPerformed

    private void btnDenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenyActionPerformed
        // TODO add your handling code here:
        request.setStatus("Declined");
        request.setOverallStatus("completed");
        JOptionPane.showMessageDialog(null, "Declined Successfully!");

        //back to page
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
        
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnDenyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeny;
    private javax.swing.JComboBox<String> cbCareTaker;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton tbnConfirm;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
