package userinterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CareTakerOrganization;
import Business.Organization.CorporateOrganization;
import Business.Organization.GovernmentOrganization;
import Business.Organization.HeadquatersOrganization;
import Business.Organization.InvestorOrganization;
import Business.Organization.LogisticOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private JPanel userProcessContainer;
    Network tempNetwork;

    UserAccount admin;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount admin, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        system = business;
        this.admin = admin;
        populateEnterpriseTable();
        populateComboBox();
        populateOrgComboBox();
        populateOrganizationComboBox();
        populateOrganizationTable();
        populateEnterpriseComboBox();
        populateEmployeeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateComboBox() {
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        for (Enterprise.EnterpriseType e : Enterprise.EnterpriseType.values()) {
            dm.addElement(e);
        }
        cbType.setModel(dm);
    }

    public void populateEnterpriseComboBox() {
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        for (Enterprise e : tempNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            dm.addElement(e);
        }
        cbEnterprise.setModel(dm);
        cbEnterprise1.setModel(dm);
    }

    public void populateOrgComboBox() {
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        if (cbEnterprise.getSelectedIndex() == 0) {
            dm.addElement(new GovernmentOrganization());
        } else if (cbEnterprise.getSelectedIndex() == 2) {
            dm.addElement(new HeadquatersOrganization());
            dm.addElement(new CareTakerOrganization());
            dm.addElement(new InvestorOrganization());
            dm.addElement(new LogisticOrganization());
            dm.addElement(new SupplierOrganization());
        } else if (cbEnterprise.getSelectedIndex() == 1) {
            dm.addElement(new CorporateOrganization());
        } else {
            dm.addElement(new NGOOrganization());
        }
        cbOrganization1.setModel(dm);
    }
    
     public void populateOrganizationComboBox() {
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        if (cbEnterprise.getSelectedIndex() == 0) {
            dm.addElement(Organization.Type.Government);
        } else if (cbEnterprise.getSelectedIndex() == 2) {
            dm.addElement(Organization.Type.Headquaters);
            dm.addElement(Organization.Type.CareTaker);
            dm.addElement(Organization.Type.Investor);
            dm.addElement(Organization.Type.Logistic);
            dm.addElement(Organization.Type.Supplier);
        } else if (cbEnterprise.getSelectedIndex() == 1) {
            dm.addElement(Organization.Type.Corporate);
        } else {
            dm.addElement(Organization.Type.NGO);
        }
        cbOrganization.setModel(dm);
     }
    
    
    public void populateEnterpriseTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseTable.getModel();
        model.setRowCount(0);

        for (Network network : system.getNetworkList()) {
            tempNetwork = network;
            if (network.getUserAccountDirectory().getUserAccountList().contains(admin)) {
                for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                    Object[] row = new Object[2];
                    row[0] = e.getName();
                    row[1] = e.getEnterpriseType();
                    model.addRow(row);
                }
                break;
            }
        }
    }

    public void populateOrganizationTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseTable1.getModel();
        model.setRowCount(0);

        for (Enterprise e : tempNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                Object[] row = new Object[2];
                row[1] = e.getName();
                row[0] = o;
                model.addRow(row);
            }
        }

    }

    public void populateEmployeeTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseTable2.getModel();
        model.setRowCount(0);

        for (Enterprise e : tempNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            System.out.println("Ente"+e.getName());
            for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                System.out.println("Org"+o.getName());
                for (Employee emp : o.getEmployeeDirectory().getEmployeeList()) {
                    Object[] row = new Object[4];
                    row[1] = e.getName();
                    row[0] = o.getName();
                    row[2] = emp;
                    row[3] = emp.getUserName();
                    model.addRow(row);
                }
            }
        }

    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        NetworkPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        createEnterpriseButton = new javax.swing.JButton();
        createEnterpriseButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox<>();
        logout4 = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbEnterprise = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        enterpriseTable1 = new javax.swing.JTable();
        createEnterpriseButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbOrganization = new javax.swing.JComboBox<>();
        createEnterpriseButton3 = new javax.swing.JButton();
        logout3 = new javax.swing.JLabel();
        EmplyeePAnel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbEnterprise1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        cbOrganization1 = new javax.swing.JComboBox<>();
        createEnterpriseButton4 = new javax.swing.JButton();
        createEnterpriseButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        enterpriseTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        txtName3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        logout2 = new javax.swing.JLabel();

        enterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseTable.setEnabled(false);
        jScrollPane1.setViewportView(enterpriseTable);

        jLabel1.setText("Name");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        createEnterpriseButton.setBackground(new java.awt.Color(204, 204, 204));
        createEnterpriseButton.setText("Create");
        createEnterpriseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseButtonActionPerformed(evt);
            }
        });

        createEnterpriseButton1.setBackground(new java.awt.Color(204, 204, 204));
        createEnterpriseButton1.setText("Delete");
        createEnterpriseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Type:");

        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        logout4.setText("Logout");
        logout4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NetworkPanelLayout = new javax.swing.GroupLayout(NetworkPanel);
        NetworkPanel.setLayout(NetworkPanelLayout);
        NetworkPanelLayout.setHorizontalGroup(
            NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetworkPanelLayout.createSequentialGroup()
                .addGroup(NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NetworkPanelLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(logout4)
                            .addGap(80, 80, 80)
                            .addGroup(NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(NetworkPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(69, 69, 69)
                                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(createEnterpriseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NetworkPanelLayout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(createEnterpriseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        NetworkPanelLayout.setVerticalGroup(
            NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetworkPanelLayout.createSequentialGroup()
                .addGroup(NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NetworkPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NetworkPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(logout4)))
                .addGap(34, 34, 34)
                .addComponent(createEnterpriseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createEnterpriseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        jTabbedPane1.addTab("Enterprise", NetworkPanel);

        jLabel3.setText("Enterprise:");

        cbEnterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterpriseActionPerformed(evt);
            }
        });

        jLabel4.setText("Name:");

        enterpriseTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization", "Enterprise"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseTable1.setEnabled(false);
        jScrollPane2.setViewportView(enterpriseTable1);

        createEnterpriseButton2.setBackground(new java.awt.Color(204, 204, 204));
        createEnterpriseButton2.setText("Delete");
        createEnterpriseButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Type:");

        cbOrganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        createEnterpriseButton3.setBackground(new java.awt.Color(204, 204, 204));
        createEnterpriseButton3.setText("Create");
        createEnterpriseButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseButton3ActionPerformed(evt);
            }
        });

        logout3.setText("Logout");
        logout3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(createEnterpriseButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(createEnterpriseButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(151, 151, 151)
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(cbEnterprise, 0, 91, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(77, 77, 77)
                                .addComponent(cbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout3))
                .addGap(18, 18, 18)
                .addComponent(createEnterpriseButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(createEnterpriseButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        jTabbedPane1.addTab("Organisation", AdminPanel);

        jLabel6.setText("Enterprise:");

        cbEnterprise1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEnterprise1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterprise1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Name:");

        cbOrganization1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        createEnterpriseButton4.setBackground(new java.awt.Color(204, 204, 204));
        createEnterpriseButton4.setText("Delete");
        createEnterpriseButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseButton4ActionPerformed(evt);
            }
        });

        createEnterpriseButton5.setBackground(new java.awt.Color(204, 204, 204));
        createEnterpriseButton5.setText("Create");
        createEnterpriseButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseButton5ActionPerformed(evt);
            }
        });

        enterpriseTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization", "Enterprise", "Employee", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseTable2.setEnabled(false);
        jScrollPane3.setViewportView(enterpriseTable2);

        jLabel8.setText("Type:");

        jLabel9.setText("Username: ");

        jLabel11.setText("Password:");

        logout2.setText("Logout");
        logout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EmplyeePAnelLayout = new javax.swing.GroupLayout(EmplyeePAnel);
        EmplyeePAnel.setLayout(EmplyeePAnelLayout);
        EmplyeePAnelLayout.setHorizontalGroup(
            EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmplyeePAnelLayout.createSequentialGroup()
                                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(createEnterpriseButton5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(logout2))
                                            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(createEnterpriseButton4)))
                                        .addGap(31, 31, 31))))
                            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbOrganization1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbEnterprise1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(88, 88, 88)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        EmplyeePAnelLayout.setVerticalGroup(
            EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(createEnterpriseButton4))
                    .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6))
                            .addComponent(cbEnterprise1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbOrganization1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(49, 49, 49)
                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7))
                            .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createEnterpriseButton5)
                    .addComponent(logout2))
                .addGap(132, 132, 132))
        );

        jTabbedPane1.addTab("Employee", EmplyeePAnel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createEnterpriseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseButtonActionPerformed
        // TODO add your handling code here:
        if (nameTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name is mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        tempNetwork.getEnterpriseDirectory().createAndAddEnterprise(nameTextField.getText(), (Enterprise.EnterpriseType) cbType.getSelectedItem());
        nameTextField.setText("");
        JOptionPane.showMessageDialog(null, "Enterprise added successfully");
        populateEnterpriseTable();
    }//GEN-LAST:event_createEnterpriseButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void createEnterpriseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createEnterpriseButton1ActionPerformed

    private void createEnterpriseButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createEnterpriseButton2ActionPerformed

    private void cbEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterpriseActionPerformed
        // TODO add your handling code here:
        populateOrganizationComboBox();
        populateOrgComboBox();
    }//GEN-LAST:event_cbEnterpriseActionPerformed

    private void createEnterpriseButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseButton3ActionPerformed
        // TODO add your handling code here:

        Enterprise e = (Enterprise) cbEnterprise.getSelectedItem();
        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
            if (o.getName().equals(txtName.getText())) {
                JOptionPane.showMessageDialog(null, "Organization already exists", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        e.getOrganizationDirectory().createOrganization((Organization.Type) cbOrganization.getSelectedItem());
        JOptionPane.showMessageDialog(null, "Organization added successfully");
        populateOrganizationTable();
        
    }//GEN-LAST:event_createEnterpriseButton3ActionPerformed

    private void cbEnterprise1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterprise1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEnterprise1ActionPerformed

    private void createEnterpriseButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createEnterpriseButton4ActionPerformed

    private void createEnterpriseButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseButton5ActionPerformed
        // TODO add your handling code here:
        
        Organization o = (Organization)cbOrganization1.getSelectedItem();
        for(Employee e:o.getEmployeeDirectory().getEmployeeList()){
            if(e.getUserName().equals(txtName2.getText())){
                JOptionPane.showMessageDialog(null, "Organization already exists", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        Employee e = new Employee();
        e.setName(txtName1.getText());
        e.setUserName(txtName2.getText());
        e.setEmailId(txtName3.getText());
        e.setPassword(String.valueOf(jPasswordField1.getPassword()));
        o.getEmployeeDirectory().getEmployeeList().add(e);
        JOptionPane.showMessageDialog(null, "Employee added successfully "+ e.getUserName());
        populateEmployeeTable();
        
        txtName1.setText("");
        txtName2.setText("");
        txtName3.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_createEnterpriseButton5ActionPerformed

    private void logout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout2MouseClicked
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logout2MouseClicked

    private void logout3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseClicked
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logout3MouseClicked

    private void logout4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout4MouseClicked
        // TODO add your handling code here:
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logout4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel EmplyeePAnel;
    private javax.swing.JPanel NetworkPanel;
    private javax.swing.JComboBox<String> cbEnterprise;
    private javax.swing.JComboBox<String> cbEnterprise1;
    private javax.swing.JComboBox<String> cbOrganization;
    private javax.swing.JComboBox<String> cbOrganization1;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JButton createEnterpriseButton;
    private javax.swing.JButton createEnterpriseButton1;
    private javax.swing.JButton createEnterpriseButton2;
    private javax.swing.JButton createEnterpriseButton3;
    private javax.swing.JButton createEnterpriseButton4;
    private javax.swing.JButton createEnterpriseButton5;
    private javax.swing.JTable enterpriseTable;
    private javax.swing.JTable enterpriseTable1;
    private javax.swing.JTable enterpriseTable2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel logout2;
    private javax.swing.JLabel logout3;
    private javax.swing.JLabel logout4;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtName3;
    // End of variables declaration//GEN-END:variables

}
