package userinterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CareTakerOrganization;
import Business.Organization.CorporateOrganization;
import Business.Organization.GovernmentOrganization;
import Business.Organization.HeadquatersOrganization;
import Business.Organization.InvestorOrganization;
import Business.Organization.LogisticOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * @author Alekhya
 * @author Apeksha
 * @author Shalini
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private JPanel userProcessContainer;
    Network tempNetwork;

    UserAccount admin;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount admin, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        system = business;
        this.admin = admin;
        populateEnterpriseTable();
        populateComboBox();
        populateOrgComboBox();
        populateOrganizationComboBox();
        populateOrganizationTable();
        populateEnterpriseComboBox();
        populateEmployeeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateComboBox() {
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        for (Enterprise.EnterpriseType e : Enterprise.EnterpriseType.values()) {
            dm.addElement(e);
        }
        cbType.setModel(dm);
    }

    public void populateEnterpriseComboBox() {
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        for (Enterprise e : tempNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            dm.addElement(e);
        }
        cbEnterprise.setModel(dm);
        cbEnterprise1.setModel(dm);
    }

    public void populateOrgComboBox() {
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        if (cbEnterprise.getSelectedIndex() == 0) {
            dm.addElement(new GovernmentOrganization());
        } else if (cbEnterprise.getSelectedIndex() == 2) {
            dm.addElement(new HeadquatersOrganization());
            dm.addElement(new CareTakerOrganization());
            dm.addElement(new InvestorOrganization());
            dm.addElement(new LogisticOrganization());
            dm.addElement(new SupplierOrganization());
        } else if (cbEnterprise.getSelectedIndex() == 1) {
            dm.addElement(new CorporateOrganization());
        } else {
            dm.addElement(new NGOOrganization());
        }
        cbOrganization1.setModel(dm);
    }
    
     public void populateOrganizationComboBox() {
        DefaultComboBoxModel dm = new DefaultComboBoxModel();
        if (cbEnterprise.getSelectedIndex() == 0) {
            dm.addElement(Organization.Type.Government);
        } else if (cbEnterprise.getSelectedIndex() == 2) {
            dm.addElement(Organization.Type.Headquaters);
            dm.addElement(Organization.Type.CareTaker);
            dm.addElement(Organization.Type.Investor);
            dm.addElement(Organization.Type.Logistic);
            dm.addElement(Organization.Type.Supplier);
        } else if (cbEnterprise.getSelectedIndex() == 1) {
            dm.addElement(Organization.Type.Corporate);
        } else {
            dm.addElement(Organization.Type.NGO);
        }
        cbOrganization.setModel(dm);
     }
    
    
    public void populateEnterpriseTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseTable.getModel();
        model.setRowCount(0);

        for (Network network : system.getNetworkList()) {
            tempNetwork = network;
            if (network.getUserAccountDirectory().getUserAccountList().contains(admin)) {
                for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                    Object[] row = new Object[2];
                    row[0] = e.getName();
                    row[1] = e.getEnterpriseType();
                    model.addRow(row);
                }
                break;
            }
        }
    }

    public void populateOrganizationTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseTable1.getModel();
        model.setRowCount(0);

        for (Enterprise e : tempNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                Object[] row = new Object[2];
                row[1] = e.getName();
                row[0] = o;
                model.addRow(row);
            }
        }

    }

    public void populateEmployeeTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseTable2.getModel();
        model.setRowCount(0);

        for (Enterprise e : tempNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            System.out.println("Ente"+e.getName());
            for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                System.out.println("Org"+o.getName());
                for (Employee emp : o.getEmployeeDirectory().getEmployeeList()) {
                    Object[] row = new Object[4];
                    row[1] = e.getName();
                    row[0] = o.getName();
                    row[2] = emp;
                    row[3] = emp.getUserName();
                    model.addRow(row);
                }
            }
        }

    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        NetworkPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        createEnterpriseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox<>();
        logout4 = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbEnterprise = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        enterpriseTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cbOrganization = new javax.swing.JComboBox<>();
        createEnterpriseButton3 = new javax.swing.JButton();
        logout3 = new javax.swing.JLabel();
        EmplyeePAnel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbEnterprise1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        cbOrganization1 = new javax.swing.JComboBox<>();
        createEnterpriseButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        enterpriseTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        txtName3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        logout2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 51));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N

        NetworkPanel.setBackground(new java.awt.Color(0, 51, 51));

        enterpriseTable.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        enterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseTable.setEnabled(false);
        jScrollPane1.setViewportView(enterpriseTable);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        nameTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        createEnterpriseButton.setBackground(new java.awt.Color(204, 204, 204));
        createEnterpriseButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createEnterpriseButton.setText("Create");
        createEnterpriseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Type:");

        cbType.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        logout4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NetworkPanelLayout = new javax.swing.GroupLayout(NetworkPanel);
        NetworkPanel.setLayout(NetworkPanelLayout);
        NetworkPanelLayout.setHorizontalGroup(
            NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetworkPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NetworkPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NetworkPanelLayout.createSequentialGroup()
                        .addComponent(createEnterpriseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(logout4)
                .addContainerGap())
        );
        NetworkPanelLayout.setVerticalGroup(
            NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetworkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(NetworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(createEnterpriseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Enterprise", NetworkPanel);

        AdminPanel.setBackground(new java.awt.Color(0, 51, 51));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enterprise:");

        cbEnterprise.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbEnterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterpriseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        enterpriseTable1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        enterpriseTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization", "Enterprise"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseTable1.setEnabled(false);
        jScrollPane2.setViewportView(enterpriseTable1);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Type:");

        cbOrganization.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbOrganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        createEnterpriseButton3.setBackground(new java.awt.Color(204, 204, 204));
        createEnterpriseButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createEnterpriseButton3.setText("Create");
        createEnterpriseButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseButton3ActionPerformed(evt);
            }
        });

        logout3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(76, 76, 76)
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbEnterprise, 0, 166, Short.MAX_VALUE)
                                    .addComponent(txtName))
                                .addGap(218, 218, 218)
                                .addComponent(cbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(142, 142, 142)
                        .addComponent(logout3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(336, 336, 336))))
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(createEnterpriseButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(createEnterpriseButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Organisation", AdminPanel);

        EmplyeePAnel.setBackground(new java.awt.Color(0, 51, 51));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enterprise:");

        cbEnterprise1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbEnterprise1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEnterprise1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterprise1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name:");

        txtName1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        cbOrganization1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        cbOrganization1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        createEnterpriseButton5.setBackground(new java.awt.Color(204, 204, 204));
        createEnterpriseButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createEnterpriseButton5.setText("Create");
        createEnterpriseButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterpriseButton5ActionPerformed(evt);
            }
        });

        enterpriseTable2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        enterpriseTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization", "Enterprise", "Employee", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterpriseTable2.setEnabled(false);
        jScrollPane3.setViewportView(enterpriseTable2);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Type:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username: ");

        txtName2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        txtName3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password:");

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        logout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout2MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email:");

        javax.swing.GroupLayout EmplyeePAnelLayout = new javax.swing.GroupLayout(EmplyeePAnel);
        EmplyeePAnel.setLayout(EmplyeePAnelLayout);
        EmplyeePAnelLayout.setHorizontalGroup(
            EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(createEnterpriseButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmplyeePAnelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmplyeePAnelLayout.createSequentialGroup()
                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel11)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmplyeePAnelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35)))
                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField1)
                            .addComponent(txtName3))
                        .addGap(581, 581, 581))
                    .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbOrganization1, javax.swing.GroupLayout.Alignment.LEADING, 0, 175, Short.MAX_VALUE)
                            .addComponent(txtName2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName1)
                            .addComponent(cbEnterprise1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        EmplyeePAnelLayout.setVerticalGroup(
            EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout2)
                .addGap(44, 44, 44)
                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EmplyeePAnelLayout.createSequentialGroup()
                        .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmplyeePAnelLayout.createSequentialGroup()
                                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cbEnterprise1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbOrganization1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(31, 31, 31)
                                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(32, 32, 32)
                                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(35, 35, 35)
                                .addGroup(EmplyeePAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmplyeePAnelLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)))
                        .addComponent(jLabel11))
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(createEnterpriseButton5)
                .addGap(89, 89, 89))
        );

        jTabbedPane1.addTab("Employee", EmplyeePAnel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createEnterpriseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseButtonActionPerformed
        // TODO add your handling code here:
        if (nameTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name is mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        tempNetwork.getEnterpriseDirectory().createAndAddEnterprise(nameTextField.getText(), (Enterprise.EnterpriseType) cbType.getSelectedItem());
        nameTextField.setText("");
        JOptionPane.showMessageDialog(null, "Enterprise added successfully");
        populateEnterpriseTable();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_createEnterpriseButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void cbEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterpriseActionPerformed
        // TODO add your handling code here:
        populateOrganizationComboBox();
        populateOrgComboBox();
    }//GEN-LAST:event_cbEnterpriseActionPerformed

    private void createEnterpriseButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseButton3ActionPerformed
        // TODO add your handling code here:

        Enterprise e = (Enterprise) cbEnterprise.getSelectedItem();
        for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
            if (o.getName().equals(txtName.getText())) {
                JOptionPane.showMessageDialog(null, "Organization already exists", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        e.getOrganizationDirectory().createOrganization((Organization.Type) cbOrganization.getSelectedItem());
        JOptionPane.showMessageDialog(null, "Organization added successfully");
        populateOrganizationTable();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_createEnterpriseButton3ActionPerformed

    private void cbEnterprise1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterprise1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEnterprise1ActionPerformed

    private void createEnterpriseButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterpriseButton5ActionPerformed
        // TODO add your handling code here:
        
        Organization o = (Organization)cbOrganization1.getSelectedItem();
        for(Employee e:o.getEmployeeDirectory().getEmployeeList()){
            if(e.getUserName().equals(txtName2.getText())){
                JOptionPane.showMessageDialog(null, "Organization already exists", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        Employee e = new Employee();
        e.setName(txtName1.getText());
        e.setUserName(txtName2.getText());
        e.setEmailId(txtName3.getText());
        e.setPassword(String.valueOf(jPasswordField1.getPassword()));
        o.getEmployeeDirectory().getEmployeeList().add(e);
        JOptionPane.showMessageDialog(null, "Employee added successfully "+ e.getUserName());
        populateEmployeeTable();
        
        txtName1.setText("");
        txtName2.setText("");
        txtName3.setText("");
        jPasswordField1.setText("");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_createEnterpriseButton5ActionPerformed

    private void logout2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout2MouseClicked
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logout2MouseClicked

    private void logout3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout3MouseClicked
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logout3MouseClicked

    private void logout4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout4MouseClicked
        // TODO add your handling code here:
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logout4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel EmplyeePAnel;
    private javax.swing.JPanel NetworkPanel;
    private javax.swing.JComboBox<String> cbEnterprise;
    private javax.swing.JComboBox<String> cbEnterprise1;
    private javax.swing.JComboBox<String> cbOrganization;
    private javax.swing.JComboBox<String> cbOrganization1;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JButton createEnterpriseButton;
    private javax.swing.JButton createEnterpriseButton3;
    private javax.swing.JButton createEnterpriseButton5;
    private javax.swing.JTable enterpriseTable;
    private javax.swing.JTable enterpriseTable1;
    private javax.swing.JTable enterpriseTable2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logout2;
    private javax.swing.JLabel logout3;
    private javax.swing.JLabel logout4;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtName3;
    // End of variables declaration//GEN-END:variables

}
